#
# This file contains configuration variables for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "datalab";
$SERVER_NAME = "172.16.2.207";
$SERVER_PORT = 8901;
$COURSE_NAME = "csapp";
$AUTOGRADE_TIMEOUT = 0;
1;
